services:
    web:
        image: ghcr.io/nquangit/ocr-captchas:main
        stop_signal: SIGINT
        volumes:
            - ./captcha_ocr_model.keras:/app/captcha_ocr_model.keras
        ports:
            - "13044:5000"
